- Las variables son contenedores para guardar valores de datos.

## Creación de Variables
- Python no tiene un comando para la declaración de variables.

- En Python, las variables son creadas en el momento en el que le asignas un valor

In [1]:
x = 5
y = "John"
print(x)
print(y)

5
John

- Las variables no necesitan ser declaradas con algún tipo en particular, y pueden cambiar de tipo después de que han sido creadas.

In [2]:
x = 4       # x is of type int
x = "Sally" # x is now of type str
print(x)

Sally

In [6]:
ruta_y_nombre_archivo0 = 'data/raw/Sleep_health_and_lifestyle_dataset_0.csv'
print(ruta_y_nombre_archivo0)

data/raw/Sleep_health_and_lifestyle_dataset_0.csv

In [7]:
import pandas as pd
tabla0 = pd.read_csv(ruta_y_nombre_archivo0)
tabla0

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000
5,6,Male,28,Software Engineer,5.9,4,30,8,Obese,140/90,85,3000
6,7,Male,29,Teacher,6.3,6,40,7,Obese,140/90,82,3500
7,8,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000
8,9,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000
9,10,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000
10,11,Male,29,Doctor,6.1,6,30,8,Normal,120/80,70,8000
11,12,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000
12,13,Male,29,Doctor,6.1,6,30,8,Normal,120/80,70,8000
13,14,Male,29,Doctor,6.0,6,30,8,Normal,120/80,70,8000
14,15,Male,29,Doctor,6.0,6,30,8,Normal,120/80,70,8000
15,16,Male,29,Doctor,6.0,6,30,8,Normal,120/80,70,8000
16,17,Female,29,Nurse,6.5,5,40,7,Normal Weight,132/87,80,4000
17,18,Male,29,Doctor,6.0,6,30,8,Normal,120/80,70,8000
18,19,Female,29,Nurse,6.5,5,40,7,Normal Weight,132/87,80,4000
19,20,Male,30,Doctor,7.6,7,75,6,Normal,120/80,70,8000
20,21,Male,30,Doctor,7.7,7,75,6,Normal,120/80,70,8000
21,22,Male,30,Doctor,7.7,7,75,6,Normal,120/80,70,8000
22,23,Male,30,Doctor,7.7,7,75,6,Normal,120/80,70,8000
23,24,Male,30,Doctor,7.7,7,75,6,Normal,120/80,70,8000
24,25,Male,30,Doctor,7.8,7,75,6,Normal,120/80,70,8000
25,26,Male,30,Doctor,7.9,7,75,6,Normal,120/80,70,8000
26,27,Male,30,Doctor,7.8,7,75,6,Normal,120/80,70,8000
27,28,Male,30,Doctor,7.9,7,75,6,Normal,120/80,70,8000
28,29,Male,30,Doctor,7.9,7,75,6,Normal,120/80,70,8000
29,30,Male,30,Doctor,7.9,7,75,6,Normal,120/80,70,8000
30,31,Female,30,Nurse,6.4,5,35,7,Normal Weight,130/86,78,4100
31,32,Female,30,Nurse,6.4,5,35,7,Normal Weight,130/86,78,4100
32,33,Female,31,Nurse,7.9,8,75,4,Normal Weight,117/76,69,6800
33,34,Male,31,Doctor,6.1,6,30,8,Normal,125/80,72,5000
34,35,Male,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000
35,36,Male,31,Doctor,6.1,6,30,8,Normal,125/80,72,5000
36,37,Male,31,Doctor,6.1,6,30,8,Normal,125/80,72,5000
37,38,Male,31,Doctor,7.6,7,75,6,Normal,120/80,70,8000
38,39,Male,31,Doctor,7.6,7,75,6,Normal,120/80,70,8000
39,40,Male,31,Doctor,7.6,7,75,6,Normal,120/80,70,8000
40,41,Male,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000
41,42,Male,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000
42,43,Male,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000

In [8]:
import pandas as pd

In [10]:
ruta_y_nombre_archivo1a = '../data/raw/Sleep_health_and_lifestyle_dataset_1.csv'
print(ruta_y_nombre_archivo1a)
tabla1a = pd.read_csv(ruta_y_nombre_archivo1a)
tabla1a

../data/raw/Sleep_health_and_lifestyle_dataset_1.csv

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps
0,39,Male,31,Doctor,7.6,7,75,6,Normal,120/80,70,8000
1,40,Male,31,Doctor,7.6,7,75,6,Normal,120/80,70,8000
2,41,Male,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000
3,42,Male,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000
4,43,Male,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000
5,44,Male,31,Doctor,7.8,7,75,6,Normal,120/80,70,8000
6,45,Male,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000
7,46,Male,31,Doctor,7.8,7,75,6,Normal,120/80,70,8000
8,47,Male,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000
9,48,Male,31,Doctor,7.8,7,75,6,Normal,120/80,70,8000
10,49,Male,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000
11,50,Male,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000
12,51,Male,32,Engineer,7.5,8,45,3,Normal,120/80,70,8000
13,52,Male,32,Engineer,7.5,8,45,3,Normal,120/80,70,8000
14,53,Male,32,Doctor,6.0,6,30,8,Normal,125/80,72,5000
15,54,Male,32,Doctor,7.6,7,75,6,Normal,120/80,70,8000
16,55,Male,32,Doctor,6.0,6,30,8,Normal,125/80,72,5000
17,56,Male,32,Doctor,6.0,6,30,8,Normal,125/80,72,5000
18,57,Male,32,Doctor,7.7,7,75,6,Normal,120/80,70,8000
19,58,Male,32,Doctor,6.0,6,30,8,Normal,125/80,72,5000
20,59,Male,32,Doctor,6.0,6,30,8,Normal,125/80,72,5000
21,60,Male,32,Doctor,7.7,7,75,6,Normal,120/80,70,8000
22,61,Male,32,Doctor,6.0,6,30,8,Normal,125/80,72,5000
23,62,Male,32,Doctor,6.0,6,30,8,Normal,125/80,72,5000
24,63,Male,32,Doctor,6.2,6,30,8,Normal,125/80,72,5000
25,64,Male,32,Doctor,6.2,6,30,8,Normal,125/80,72,5000
26,65,Male,32,Doctor,6.2,6,30,8,Normal,125/80,72,5000
27,66,Male,32,Doctor,6.2,6,30,8,Normal,125/80,72,5000
28,67,Male,32,Accountant,7.2,8,50,6,Normal Weight,118/76,68,7000
29,68,Male,33,Doctor,6.0,6,30,8,Normal,125/80,72,5000
30,69,Female,33,Scientist,6.2,6,50,6,Overweight,128/85,76,5500
31,70,Female,33,Scientist,6.2,6,50,6,Overweight,128/85,76,5500
32,71,Male,33,Doctor,6.1,6,30,8,Normal,125/80,72,5000
33,72,Male,33,Doctor,6.1,6,30,8,Normal,125/80,72,5000
34,73,Male,33,Doctor,6.1,6,30,8,Normal,125/80,72,5000
35,74,Male,33,Doctor,6.1,6,30,8,Normal,125/80,72,5000
36,75,Male,33,Doctor,6.0,6,30,8,Normal,125/80,72,5000
37,76,Male,33,Doctor,6.0,6,30,8,Normal,125/80,72,5000
38,77,Male,33,Doctor,6.0,6,30,8,Normal,125/80,72,5000
39,78,Male,33,Doctor,6.0,6,30,8,Normal,125/80,72,5000
40,79,Male,33,Doctor,6.0,6,30,8,Normal,125/80,72,5000
41,80,Male,33,Doctor,6.0,6,30,8,Normal,125/80,72,5000
42,81,Female,34,Scientist,5.8,4,32,8,Overweight,131/86,81,5200

In [11]:
! pwd

/app/my_data

In [12]:
#ruta_y_nombre_archivo1 = '/Users/josealfredomendezbarrera/Documents/prsnl/DSCertification_FMAT/data/raw/Sleep_health_and_lifestyle_dataset_1.csv'
ruta_y_nombre_archivo1 = 'data/raw/Sleep_health_and_lifestyle_dataset_1.csv'
print(ruta_y_nombre_archivo1)
tabla1 = pd.read_csv(ruta_y_nombre_archivo1)
tabla1

data/raw/Sleep_health_and_lifestyle_dataset_1.csv

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps
0,39,Male,31,Doctor,7.6,7,75,6,Normal,120/80,70,8000
1,40,Male,31,Doctor,7.6,7,75,6,Normal,120/80,70,8000
2,41,Male,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000
3,42,Male,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000
4,43,Male,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000
5,44,Male,31,Doctor,7.8,7,75,6,Normal,120/80,70,8000
6,45,Male,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000
7,46,Male,31,Doctor,7.8,7,75,6,Normal,120/80,70,8000
8,47,Male,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000
9,48,Male,31,Doctor,7.8,7,75,6,Normal,120/80,70,8000
10,49,Male,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000
11,50,Male,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000
12,51,Male,32,Engineer,7.5,8,45,3,Normal,120/80,70,8000
13,52,Male,32,Engineer,7.5,8,45,3,Normal,120/80,70,8000
14,53,Male,32,Doctor,6.0,6,30,8,Normal,125/80,72,5000
15,54,Male,32,Doctor,7.6,7,75,6,Normal,120/80,70,8000
16,55,Male,32,Doctor,6.0,6,30,8,Normal,125/80,72,5000
17,56,Male,32,Doctor,6.0,6,30,8,Normal,125/80,72,5000
18,57,Male,32,Doctor,7.7,7,75,6,Normal,120/80,70,8000
19,58,Male,32,Doctor,6.0,6,30,8,Normal,125/80,72,5000
20,59,Male,32,Doctor,6.0,6,30,8,Normal,125/80,72,5000
21,60,Male,32,Doctor,7.7,7,75,6,Normal,120/80,70,8000
22,61,Male,32,Doctor,6.0,6,30,8,Normal,125/80,72,5000
23,62,Male,32,Doctor,6.0,6,30,8,Normal,125/80,72,5000
24,63,Male,32,Doctor,6.2,6,30,8,Normal,125/80,72,5000
25,64,Male,32,Doctor,6.2,6,30,8,Normal,125/80,72,5000
26,65,Male,32,Doctor,6.2,6,30,8,Normal,125/80,72,5000
27,66,Male,32,Doctor,6.2,6,30,8,Normal,125/80,72,5000
28,67,Male,32,Accountant,7.2,8,50,6,Normal Weight,118/76,68,7000
29,68,Male,33,Doctor,6.0,6,30,8,Normal,125/80,72,5000
30,69,Female,33,Scientist,6.2,6,50,6,Overweight,128/85,76,5500
31,70,Female,33,Scientist,6.2,6,50,6,Overweight,128/85,76,5500
32,71,Male,33,Doctor,6.1,6,30,8,Normal,125/80,72,5000
33,72,Male,33,Doctor,6.1,6,30,8,Normal,125/80,72,5000
34,73,Male,33,Doctor,6.1,6,30,8,Normal,125/80,72,5000
35,74,Male,33,Doctor,6.1,6,30,8,Normal,125/80,72,5000
36,75,Male,33,Doctor,6.0,6,30,8,Normal,125/80,72,5000
37,76,Male,33,Doctor,6.0,6,30,8,Normal,125/80,72,5000
38,77,Male,33,Doctor,6.0,6,30,8,Normal,125/80,72,5000
39,78,Male,33,Doctor,6.0,6,30,8,Normal,125/80,72,5000
40,79,Male,33,Doctor,6.0,6,30,8,Normal,125/80,72,5000
41,80,Male,33,Doctor,6.0,6,30,8,Normal,125/80,72,5000
42,81,Female,34,Scientist,5.8,4,32,8,Overweight,131/86,81,5200

## Casting

- Si se prefiere o necesita especificar el tipo de dato de una variable, esto puede ser realizado con un *casteo*.

In [13]:
x = str(3)    # x will be '3'
y = int(3)    # y will be 3
z = float(3)  # z will be 3.0
print(x)
print(y)
print(z)

3
3
3.0

## Obtener el tipo de dato

- Se puede obtener el tipo de dato de una variable con la función `type()`.

In [14]:
x = 5
y = "John"
print(type(x))
print(type(y))

<class 'int'>
<class 'str'>

- String variables can be declared either by using single or double quotes:

In [15]:
type(tabla1a)

pandas.core.frame.DataFrame

In [16]:
tabla1a['Person ID']

0     39
1     40
2     41
3     42
4     43
5     44
6     45
7     46
8     47
9     48
10    49
11    50
12    51
13    52
14    53
15    54
16    55
17    56
18    57
19    58
20    59
21    60
22    61
23    62
24    63
25    64
26    65
27    66
28    67
29    68
30    69
31    70
32    71
33    72
34    73
35    74
36    75
37    76
38    77
39    78
40    79
41    80
42    81
Name: Person ID, dtype: int64

In [17]:
type(tabla1a['Person ID'])

pandas.core.series.Series

In [18]:
len(tabla1a)

43

In [19]:
tabla1a['Person ID'][42]

81

In [20]:
type(tabla1a['Person ID'][42])

numpy.int64

In [21]:
tabla1a['Occupation']

0         Doctor
1         Doctor
2         Doctor
3         Doctor
4         Doctor
5         Doctor
6         Doctor
7         Doctor
8         Doctor
9         Doctor
10        Doctor
11        Doctor
12      Engineer
13      Engineer
14        Doctor
15        Doctor
16        Doctor
17        Doctor
18        Doctor
19        Doctor
20        Doctor
21        Doctor
22        Doctor
23        Doctor
24        Doctor
25        Doctor
26        Doctor
27        Doctor
28    Accountant
29        Doctor
30     Scientist
31     Scientist
32        Doctor
33        Doctor
34        Doctor
35        Doctor
36        Doctor
37        Doctor
38        Doctor
39        Doctor
40        Doctor
41        Doctor
42     Scientist
Name: Occupation, dtype: object

In [22]:
tabla1a.columns

Index(['Person ID', 'Gender', 'Age', 'Occupation', 'Sleep Duration',
       'Quality of Sleep', 'Physical Activity Level', 'Stress Level',
       'BMI Category', 'Blood Pressure', 'Heart Rate', 'Daily Steps'],
      dtype='object')

In [23]:
type(tabla1a['Occupation'][0])

str

In [24]:
x = "John"
# is the same as
x = 'John'

## Case-Sensitive

- Las variables son *case-sensitive*.

In [25]:
a = 4
A = "Sally"
#A will not overwrite a
print(a)
print(A)

4
Sally

[Python: Nombre de Variables](https://www.w3schools.com/python/python_variables_names.asp)

=========================
=========================

# Asignar múltiples valores

## Varios valores a múltiples variables
- Python permite asignar valores a múltiples variables en una línea:

In [26]:
x, y, z = "Orange", "Banana", "Cherry"
print(x)
print(y)
print(z)

Orange
Banana
Cherry

## Un valor a múltiples variables

- También es posible asignar el mismo valor a múltiples variables en una línea:

In [27]:
x = y = z = "Orange"
print(x)
print(y)
print(z)

Orange
Orange
Orange

## Desempaquetar una colección de datos
- Si se tiene una colección o arreglo de valores en una lista, tuple, etc, Python permite extraer los valores en variables:

In [28]:
fruits = ["apple", "banana", "cherry"]
print(fruits)
x, y, z = fruits
print(x)
print(y)
print(z)

['apple', 'banana', 'cherry']
apple
banana
cherry

- Más acerca de [desempaquetar `tuples`](https://www.w3schools.com/python/python_tuples_unpack.asp)

## Variables Globales

- Las variables que son creadas fuera de una función son conocidas como **variables globales** 

- Las variables globales pueden ser usadas por cualquiera, tanto dentro como fuera de funciones

In [29]:
x = "awesome"

def myfunc():
  print("Python is " + x)

myfunc()

Python is awesome

In [30]:
def reading_a_file(x):
  print("Leeremos el siguiente archivo: \n \n " + x)

reading_a_file(x=ruta_y_nombre_archivo0)

Leeremos el siguiente archivo:

 data/raw/Sleep_health_and_lifestyle_dataset_0.csv

In [31]:
reading_a_file(x=ruta_y_nombre_archivo1a)

Leeremos el siguiente archivo:

 ../data/raw/Sleep_health_and_lifestyle_dataset_1.csv

- Si se ha creado una variable dentro de una función, ésta será local y sólo podrá ser usada adentro de la función. La variable global con el mismo nombre se mantendrá global y con su valor original

If you create a variable with the same name inside a function, this variable will be local, and can only be used inside the function. The global variable with the same name will remain as it was, global and with the original value.

In [32]:
def sumcols(tabla, columna1, columna2):
    return tabla[columna1]+tabla[columna2]

In [34]:
#sumcols(tabla = tabla1a.tail(5).append(tabla1a.head(5)), columna1 = 'Sleep Duration', columna2 = 'Quality of Sleep')
sumcols(tabla = pd.concat([tabla1a.tail(5),tabla1a.head(5)]), columna1 = 'Sleep Duration', columna2 = 'Quality of Sleep')

38    12.0
39    12.0
40    12.0
41    12.0
42     9.8
0     14.6
1     14.6
2     14.7
3     14.7
4     14.7
dtype: float64

In [35]:
tabla1a.columns

Index(['Person ID', 'Gender', 'Age', 'Occupation', 'Sleep Duration',
       'Quality of Sleep', 'Physical Activity Level', 'Stress Level',
       'BMI Category', 'Blood Pressure', 'Heart Rate', 'Daily Steps'],
      dtype='object')

In [36]:
type(tabla1a['Age'][0])

numpy.int64

In [37]:
type(tabla1a['Sleep Duration'][0])

numpy.float64

In [39]:
sumcols(tabla = pd.concat([tabla1a.tail(5),tabla1a.head(5)]), columna1 = 'Age', columna2 = 'Gender')

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
[

In [40]:
tablanueva = pd.concat([tabla1a[20:25],tabla1a[10:15]])
tablanueva

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps
20,59,Male,32,Doctor,6.0,6,30,8,Normal,125/80,72,5000
21,60,Male,32,Doctor,7.7,7,75,6,Normal,120/80,70,8000
22,61,Male,32,Doctor,6.0,6,30,8,Normal,125/80,72,5000
23,62,Male,32,Doctor,6.0,6,30,8,Normal,125/80,72,5000
24,63,Male,32,Doctor,6.2,6,30,8,Normal,125/80,72,5000
10,49,Male,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000
11,50,Male,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000
12,51,Male,32,Engineer,7.5,8,45,3,Normal,120/80,70,8000
13,52,Male,32,Engineer,7.5,8,45,3,Normal,120/80,70,8000
14,53,Male,32,Doctor,6.0,6,30,8,Normal,125/80,72,5000

In [41]:
tablanueva['Sleep Duration']

20    6.0
21    7.7
22    6.0
23    6.0
24    6.2
10    7.7
11    7.7
12    7.5
13    7.5
14    6.0
Name: Sleep Duration, dtype: float64

In [42]:
tablanueva['Sleep Duration'].astype('category') + tablanueva['Age']

TypeError: Object with dtype category cannot perform the numpy op add

In [43]:
x = "awesome"

def myfunc():
    x = "fantastic"
    print("Python is " + x)

myfunc()

print("Python is " + x)

Python is fantastic
Python is awesome

### The global Keyword

- Normalmente, cuando se crea una variable adentro de una función, esta variable es local y sólo puede ser usada adentro de la función.

- Sin embargo, para crear una variable global desde dentro de una función, se puede utilizar la *palabra clave* **global**

In [44]:
def myfunc():
    global x
    x = "UUUUUUFAAAAA"

myfunc()

print("Python is " + x)

Python is UUUUUUFAAAAA

- También se utiliza la palabra clave **global** para cambiar el valor de una variable global desde dentro de una función

In [45]:
x = "awesome"

def myfunc():
    global x
    x = "fantastic"

myfunc()

print("Python is " + x)

Python is fantastic